version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/meghrathod/shorty"

[[transformers]]
name = "prettier"

[[transformers]]
name = "gofmt"
